import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Cleaning up existing data...');
  // Delete existing data first to avoid conflicts
  await prisma.auditEvent.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.order.deleteMany();
  await prisma.product.deleteMany();
  await prisma.policy.deleteMany();
  await prisma.merchant.deleteMany();

  console.log('Seeding data...');

  // Create Merchants
  const sportGear = await prisma.merchant.create({
    data: {
      id: 'merchant_sportgear',
      name: 'SportGear India',
      aiEnabled: true,
      currency: 'INR',
    },
  });

  const techMart = await prisma.merchant.create({
    data: {
      id: 'merchant_techmart',
      name: 'TechMart',
      aiEnabled: true,
      currency: 'INR',
    },
  });

  console.log('Created Merchants');

  // Create Policies
  await prisma.policy.create({
    data: {
      merchantId: sportGear.id,
      maxAutoSpend: 500000, // ₹5,000
      approvalThreshold: 1000000, // ₹10,000
      maxDiscountPct: 15,
      restrictedCategories: ['gift_cards'],
      minStock: 2,
      maxRetries: 1,
    },
  });

  await prisma.policy.create({
    data: {
      merchantId: techMart.id,
      maxAutoSpend: 300000, // ₹3,000
      approvalThreshold: 500000, // ₹5,000
      maxDiscountPct: 10,
      restrictedCategories: ['gift_cards', 'high_value_electronics'],
      minStock: 3,
      maxRetries: 2,
    },
  });

  console.log('Created Policies');

  // Create Products for SportGear India
  const sportGearProducts = [
    // running_shoes
    {
      merchantId: sportGear.id,
      sku: 'SG-RS-001',
      title: 'Nike Air Zoom Pegasus',
      description: 'A legendary running shoe that offers a responsive and springy ride. Perfect for everyday training runs on the road. Features breathable mesh upper for maximum comfort.',
      category: 'running_shoes',
      price: 449900,
      stock: 42,
      deliveryDays: 3,
      returnPolicy: '7-day return',
      attributes: { brand: 'Nike', color: 'Black/White', material: 'Mesh', gender: 'Unisex' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-RS-002',
      title: 'Adidas Ultraboost',
      description: 'Experience incredible energy return and comfort with these premium running shoes. The Primeknit upper adapts to your foot\'s shape. Ideal for long distance running.',
      category: 'running_shoes',
      price: 899900,
      stock: 15,
      deliveryDays: 2,
      returnPolicy: '7-day return',
      attributes: { brand: 'Adidas', color: 'Core Black', material: 'Primeknit', gender: 'Men' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-RS-003',
      title: 'Puma Velocity Nitro',
      description: 'Lightweight and highly responsive running shoes with advanced nitrogen-injected foam technology. Provides superior cushioning and traction on all surfaces.',
      category: 'running_shoes',
      price: 399900,
      stock: 28,
      deliveryDays: 4,
      returnPolicy: '7-day return',
      attributes: { brand: 'Puma', color: 'Neon Green', material: 'Synthetic', gender: 'Women' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-RS-004',
      title: 'Asics Gel-Kayano',
      description: 'Offers excellent stability and support for overpronators. Features legendary GEL cushioning system for shock absorption. Durable rubber outsole for long-lasting wear.',
      category: 'running_shoes',
      price: 649900,
      stock: 35,
      deliveryDays: 5,
      returnPolicy: '7-day return',
      attributes: { brand: 'Asics', color: 'Blue/Silver', material: 'Mesh', gender: 'Men' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-RS-005',
      title: 'New Balance Fresh Foam',
      description: 'Ultra-cushioned running shoe designed for unmatched comfort. The plush midsole provides a cloud-like feel underfoot. Great for recovery runs or long walks.',
      category: 'running_shoes',
      price: 529900,
      stock: 20,
      deliveryDays: 3,
      returnPolicy: '7-day return',
      attributes: { brand: 'New Balance', color: 'Grey', material: 'Textile', gender: 'Women' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-RS-006',
      title: 'Skechers GoRun',
      description: 'Minimalist and lightweight running shoe for an agile and fast feel. Breathable upper keeps your feet cool. A great choice for short to medium distance runs.',
      category: 'running_shoes',
      price: 299900,
      stock: 50,
      deliveryDays: 2,
      returnPolicy: '7-day return',
      attributes: { brand: 'Skechers', color: 'Navy', material: 'Knit', gender: 'Unisex' },
    },
    // fitness
    {
      merchantId: sportGear.id,
      sku: 'SG-FIT-001',
      title: 'Yoga Mat Premium',
      description: 'High-density, non-slip yoga mat that provides excellent cushioning and joint support. Easy to clean and comes with a carrying strap. Perfect for yoga, pilates, and floor exercises.',
      category: 'fitness',
      price: 129900,
      stock: 45,
      deliveryDays: 3,
      returnPolicy: '7-day return',
      attributes: { brand: 'GripFit', color: 'Purple', thickness: '6mm', material: 'TPE' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-FIT-002',
      title: 'Resistance Bands Set',
      description: 'Set of 5 resistance bands with varying tension levels. Includes handles, ankle straps, and a door anchor for a full-body workout. Comes in a convenient travel bag.',
      category: 'fitness',
      price: 79900,
      stock: 30,
      deliveryDays: 2,
      returnPolicy: '7-day return',
      attributes: { brand: 'FlexCore', color: 'Multicolor', pieces: 5, material: 'Latex' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-FIT-003',
      title: 'Kettlebell 16kg',
      description: 'Cast iron kettlebell with a durable powder-coated finish for an excellent grip. Wide handle allows for comfortable two-handed swings. Essential for strength and conditioning.',
      category: 'fitness',
      price: 249900,
      stock: 12,
      deliveryDays: 5,
      returnPolicy: '7-day return',
      attributes: { brand: 'IronBull', color: 'Black', weight: '16kg', material: 'Cast Iron' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-FIT-004',
      title: 'Jump Rope Pro',
      description: 'Adjustable speed jump rope with smooth ball bearings for fast spinning. Lightweight aluminum handles for a comfortable grip. Great for cardio and double unders.',
      category: 'fitness',
      price: 59900,
      stock: 48,
      deliveryDays: 2,
      returnPolicy: '7-day return',
      attributes: { brand: 'SpeedFit', color: 'Silver/Black', type: 'Speed', material: 'Steel Wire' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-FIT-005',
      title: 'Foam Roller',
      description: 'High-density EVA foam roller for deep tissue massage and muscle recovery. Helps relieve muscle tension and improve flexibility. Essential for pre and post-workout routines.',
      category: 'fitness',
      price: 89900,
      stock: 35,
      deliveryDays: 3,
      returnPolicy: '7-day return',
      attributes: { brand: 'RecoverPro', color: 'Blue', size: '18 inch', material: 'EVA Foam' },
    },
    // accessories
    {
      merchantId: sportGear.id,
      sku: 'SG-ACC-001',
      title: 'Sports Water Bottle',
      description: 'BPA-free, leak-proof sports water bottle with a convenient flip-top lid. 1-liter capacity to keep you hydrated during long workouts. Features measurement markings.',
      category: 'accessories',
      price: 49900,
      stock: 50,
      deliveryDays: 2,
      returnPolicy: '7-day return',
      attributes: { brand: 'Hydrate+', color: 'Cyan', capacity: '1L', material: 'Tritan' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-ACC-002',
      title: 'Running Armband',
      description: 'Sweat-resistant running armband for smartphones up to 6.5 inches. Features a clear touch-sensitive screen cover and a key pocket. Adjustable strap for a secure fit.',
      category: 'accessories',
      price: 39900,
      stock: 25,
      deliveryDays: 3,
      returnPolicy: '7-day return',
      attributes: { brand: 'RunTech', color: 'Black', size: 'Adjustable', material: 'Neoprene' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-ACC-003',
      title: 'Gym Gloves',
      description: 'Premium weightlifting gloves with wrist support and padded palms. Prevents calluses and improves grip during heavy lifts. Breathable mesh backing for comfort.',
      category: 'accessories',
      price: 69900,
      stock: 38,
      deliveryDays: 4,
      returnPolicy: '7-day return',
      attributes: { brand: 'GripPower', color: 'Black/Red', size: 'L', material: 'Leather/Mesh' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-ACC-004',
      title: 'Sweatband Set',
      description: 'Includes one headband and two wristbands made of highly absorbent cotton terry cloth. Keeps sweat out of your eyes and off your hands during intense workouts.',
      category: 'accessories',
      price: 29900,
      stock: 45,
      deliveryDays: 2,
      returnPolicy: '7-day return',
      attributes: { brand: 'SweatStop', color: 'White', pieces: 3, material: 'Cotton' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-ACC-005',
      title: 'Sports Sunglasses',
      description: 'Lightweight polarized sports sunglasses with UV400 protection. Wraparound design ensures a secure fit during running or cycling. Reduces glare and eye strain.',
      category: 'accessories',
      price: 149900,
      stock: 18,
      deliveryDays: 3,
      returnPolicy: '7-day return',
      attributes: { brand: 'VisionPro', color: 'Matte Black', lens: 'Polarized', protection: 'UV400' },
    },
    // clothing
    {
      merchantId: sportGear.id,
      sku: 'SG-CLO-001',
      title: 'Dry-Fit Running Tee',
      description: 'Moisture-wicking, breathable t-shirt designed for active performance. Quick-drying fabric keeps you comfortable and focused. Features reflective details for low-light visibility.',
      category: 'clothing',
      price: 99900,
      stock: 40,
      deliveryDays: 3,
      returnPolicy: '7-day return',
      attributes: { brand: 'ActiveWear', color: 'Neon Yellow', size: 'M', material: 'Polyester' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-CLO-002',
      title: 'Compression Leggings',
      description: 'High-performance compression leggings that support muscles and improve blood flow. Four-way stretch fabric offers maximum mobility. Includes a hidden pocket for keys.',
      category: 'clothing',
      price: 179900,
      stock: 22,
      deliveryDays: 4,
      returnPolicy: '7-day return',
      attributes: { brand: 'FlexFit', color: 'Charcoal', size: 'S', gender: 'Women' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-CLO-003',
      title: 'Windbreaker Jacket',
      description: 'Lightweight, water-resistant windbreaker jacket for outdoor training. Packable design allows easy storage. Features an adjustable hood and zippered pockets.',
      category: 'clothing',
      price: 299900,
      stock: 15,
      deliveryDays: 5,
      returnPolicy: '7-day return',
      attributes: { brand: 'WeatherShield', color: 'Royal Blue', size: 'L', material: 'Nylon' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-CLO-004',
      title: 'Sports Shorts',
      description: 'Comfortable athletic shorts with a breathable inner liner. Elastic waistband with an internal drawcord for an adjustable fit. Perfect for running, gym, or casual wear.',
      category: 'clothing',
      price: 79900,
      stock: 35,
      deliveryDays: 2,
      returnPolicy: '7-day return',
      attributes: { brand: 'ActiveWear', color: 'Black', size: 'M', material: 'Polyester Blend' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-CLO-005',
      title: 'Running Socks 3-Pack',
      description: 'Cushioned running socks with arch support and targeted ventilation zones. Anti-blister technology ensures comfort on long runs. Pack contains three pairs.',
      category: 'clothing',
      price: 49900,
      stock: 50,
      deliveryDays: 2,
      returnPolicy: '7-day return',
      attributes: { brand: 'FootPro', color: 'White/Grey', pack: 3, material: 'Cotton/Spandex' },
    },
    // gift_cards
    {
      merchantId: sportGear.id,
      sku: 'SG-GC-500',
      title: '₹500 Gift Card',
      description: 'A digital gift card worth ₹500. Perfect for treating a friend or family member to some new sports gear. Delivered instantly via email.',
      category: 'gift_cards',
      price: 50000,
      stock: 999,
      deliveryDays: 1,
      returnPolicy: 'No returns',
      attributes: { type: 'Digital', value: '500 INR' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-GC-1000',
      title: '₹1,000 Gift Card',
      description: 'A digital gift card worth ₹1,000. Give the gift of choice from our wide selection of athletic apparel and equipment. Valid for 1 year.',
      category: 'gift_cards',
      price: 100000,
      stock: 999,
      deliveryDays: 1,
      returnPolicy: 'No returns',
      attributes: { type: 'Digital', value: '1000 INR' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-GC-2500',
      title: '₹2,500 Gift Card',
      description: 'A digital gift card worth ₹2,500. The ideal present for the fitness enthusiast in your life. Can be used for any product in store.',
      category: 'gift_cards',
      price: 250000,
      stock: 999,
      deliveryDays: 1,
      returnPolicy: 'No returns',
      attributes: { type: 'Digital', value: '2500 INR' },
    },
    {
      merchantId: sportGear.id,
      sku: 'SG-GC-5000',
      title: '₹5,000 Gift Card',
      description: 'A digital gift card worth ₹5,000. For serious athletes looking to upgrade their gear. Instantly redeemable online.',
      category: 'gift_cards',
      price: 500000,
      stock: 999,
      deliveryDays: 1,
      returnPolicy: 'No returns',
      attributes: { type: 'Digital', value: '5000 INR' },
    },
  ];

  for (const product of sportGearProducts) {
    await prisma.product.create({ data: product });
  }

  // Create Products for TechMart
  const techMartProducts = [
    // smartphones
    {
      merchantId: techMart.id,
      sku: 'TM-SP-001',
      title: 'Budget Phone X1',
      description: 'An affordable smartphone with all the essential features. Reliable battery life and a decent camera for everyday use. Great value for money.',
      category: 'smartphones',
      price: 899900,
      stock: 45,
      deliveryDays: 3,
      returnPolicy: '30-day return',
      attributes: { brand: 'TechBrand', color: 'Black', storage: '64GB', ram: '4GB' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-SP-002',
      title: 'Mid-Range Pro',
      description: 'A well-balanced smartphone offering excellent performance and camera quality. Features a smooth 90Hz display and fast charging support. The sweet spot of price and features.',
      category: 'smartphones',
      price: 1599900,
      stock: 30,
      deliveryDays: 4,
      returnPolicy: '30-day return',
      attributes: { brand: 'TechBrand', color: 'Blue', storage: '128GB', ram: '6GB' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-SP-003',
      title: 'Flagship Ultra',
      description: 'The ultimate smartphone experience with a top-tier processor, stunning AMOLED display, and professional-grade camera system. Premium build quality and features.',
      category: 'smartphones',
      price: 4999900,
      stock: 15,
      deliveryDays: 2,
      returnPolicy: '30-day return',
      attributes: { brand: 'PremiumTech', color: 'Silver', storage: '256GB', ram: '12GB' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-SP-004',
      title: 'Gaming Phone',
      description: 'Designed specifically for mobile gamers, featuring shoulder triggers, advanced cooling, and a 144Hz refresh rate display. Delivers uncompromised gaming performance.',
      category: 'smartphones',
      price: 2999900,
      stock: 20,
      deliveryDays: 5,
      returnPolicy: '30-day return',
      attributes: { brand: 'GameMaster', color: 'Red/Black', storage: '256GB', ram: '8GB' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-SP-005',
      title: 'Camera Phone Plus',
      description: 'Capture the world in stunning detail with a 108MP main sensor and powerful zoom capabilities. Features AI-enhanced photography modes for perfect shots every time.',
      category: 'smartphones',
      price: 2299900,
      stock: 25,
      deliveryDays: 3,
      returnPolicy: '30-day return',
      attributes: { brand: 'PhotoPro', color: 'White', storage: '128GB', ram: '8GB' },
    },
    // accessories
    {
      merchantId: techMart.id,
      sku: 'TM-ACC-001',
      title: 'USB-C Cable',
      description: 'Durable braided USB-C to USB-C cable supporting up to 60W fast charging and high-speed data transfer. Length is 1.5 meters.',
      category: 'accessories',
      price: 29900,
      stock: 50,
      deliveryDays: 2,
      returnPolicy: '7-day return',
      attributes: { brand: 'ChargePlus', color: 'Black', length: '1.5m', type: 'USB-C' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-ACC-002',
      title: 'Phone Case',
      description: 'Rugged phone case offering military-grade drop protection. Features raised edges to protect the screen and camera module. Compatible with major smartphone models.',
      category: 'accessories',
      price: 49900,
      stock: 40,
      deliveryDays: 3,
      returnPolicy: '7-day return',
      attributes: { brand: 'ArmorCase', color: 'Clear', material: 'TPU/PC' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-ACC-003',
      title: 'Screen Protector',
      description: 'Tempered glass screen protector with 9H hardness. Protects against scratches and shatters while maintaining touch sensitivity and clarity. Includes easy installation kit.',
      category: 'accessories',
      price: 19900,
      stock: 50,
      deliveryDays: 2,
      returnPolicy: '7-day return',
      attributes: { brand: 'GlassGuard', material: 'Tempered Glass', hardness: '9H' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-ACC-004',
      title: 'Wireless Charger',
      description: 'Fast 15W wireless charging pad with a sleek design. Compatible with all Qi-enabled devices. Features an LED indicator and overcharge protection.',
      category: 'accessories',
      price: 149900,
      stock: 35,
      deliveryDays: 4,
      returnPolicy: '7-day return',
      attributes: { brand: 'PowerPad', color: 'White', wattage: '15W' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-ACC-005',
      title: 'Power Bank 20000mAh',
      description: 'High-capacity power bank capable of charging your phone multiple times. Features dual USB output ports and supports fast charging protocols. Compact and travel-friendly.',
      category: 'accessories',
      price: 199900,
      stock: 25,
      deliveryDays: 3,
      returnPolicy: '7-day return',
      attributes: { brand: 'EnergyGo', color: 'Black', capacity: '20000mAh', ports: 2 },
    },
    // audio
    {
      merchantId: techMart.id,
      sku: 'TM-AUD-001',
      title: 'Wireless Earbuds',
      description: 'True wireless earbuds with Active Noise Cancellation and immersive sound. Up to 24 hours of total playtime with the charging case. Water-resistant design.',
      category: 'audio',
      price: 249900,
      stock: 40,
      deliveryDays: 3,
      returnPolicy: '30-day return',
      attributes: { brand: 'SoundBeat', color: 'White', type: 'TWS', feature: 'ANC' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-AUD-002',
      title: 'Over-Ear Headphones',
      description: 'Premium over-ear wireless headphones with hi-res audio support and powerful bass. Plush ear cushions provide all-day comfort. Features a built-in microphone for calls.',
      category: 'audio',
      price: 499900,
      stock: 20,
      deliveryDays: 4,
      returnPolicy: '30-day return',
      attributes: { brand: 'AuraSound', color: 'Black', type: 'Over-Ear', connection: 'Bluetooth 5.0' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-AUD-003',
      title: 'Bluetooth Speaker',
      description: 'Portable Bluetooth speaker delivering 360-degree loud and clear sound. IP67 waterproof and dustproof, making it perfect for outdoor adventures. 12-hour battery life.',
      category: 'audio',
      price: 349900,
      stock: 30,
      deliveryDays: 3,
      returnPolicy: '30-day return',
      attributes: { brand: 'BoomBox', color: 'Blue', waterproof: 'IP67', playtime: '12 hours' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-AUD-004',
      title: 'Neckband Earphones',
      description: 'Comfortable wireless neckband earphones designed for sports and active lifestyles. Features magnetic ear-tips and a flexible band. Offers 15 hours of continuous playback.',
      category: 'audio',
      price: 99900,
      stock: 45,
      deliveryDays: 2,
      returnPolicy: '30-day return',
      attributes: { brand: 'SportSound', color: 'Neon Green', type: 'Neckband' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-AUD-005',
      title: 'Studio Monitors',
      description: 'Professional grade active studio monitors for precise audio mixing and production. Delivers a flat frequency response and detailed soundstage. Sold as a pair.',
      category: 'audio',
      price: 799900,
      stock: 10,
      deliveryDays: 5,
      returnPolicy: '30-day return',
      attributes: { brand: 'ProAudio', color: 'Black', type: 'Active Monitors', power: '50W' },
    },
    // high_value_electronics
    {
      merchantId: techMart.id,
      sku: 'TM-HVE-001',
      title: 'Laptop Pro 16',
      description: 'High-performance laptop featuring a powerful 8-core processor, dedicated graphics, and a stunning 16-inch Retina display. Ideal for creative professionals and heavy multitasking.',
      category: 'high_value_electronics',
      price: 8999900,
      stock: 8,
      deliveryDays: 5,
      returnPolicy: '30-day return',
      attributes: { brand: 'TechPro', color: 'Space Grey', ram: '16GB', storage: '512GB SSD' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-HVE-002',
      title: 'Gaming Monitor',
      description: '27-inch 1440p gaming monitor with an ultra-fast 165Hz refresh rate and 1ms response time. Features FreeSync premium for tear-free gaming. Adjustable stand included.',
      category: 'high_value_electronics',
      price: 3499900,
      stock: 12,
      deliveryDays: 6,
      returnPolicy: '30-day return',
      attributes: { brand: 'ViewMax', size: '27 inch', resolution: '1440p', refreshRate: '165Hz' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-HVE-003',
      title: 'Mechanical Keyboard',
      description: 'Premium mechanical keyboard with tactile Cherry MX Brown switches. Fully customizable RGB backlighting per key. Sturdy aluminum frame and detachable USB-C cable.',
      category: 'high_value_electronics',
      price: 699900,
      stock: 25,
      deliveryDays: 3,
      returnPolicy: '30-day return',
      attributes: { brand: 'TypeMaster', switches: 'Cherry MX Brown', layout: 'Full Size' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-HVE-004',
      title: 'Wireless Mouse',
      description: 'Ergonomic wireless mouse designed for productivity and comfort. Features a high-precision sensor, customizable buttons, and seamless multi-device switching. Rechargeable battery.',
      category: 'high_value_electronics',
      price: 249900,
      stock: 35,
      deliveryDays: 4,
      returnPolicy: '30-day return',
      attributes: { brand: 'ClickPro', color: 'Graphite', connectivity: 'Bluetooth/USB Receiver' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-HVE-005',
      title: 'Webcam 4K',
      description: 'Professional 4K webcam perfect for streaming and video conferencing. Features autofocus, HDR support, and a built-in privacy cover. Dual omnidirectional mics.',
      category: 'high_value_electronics',
      price: 599900,
      stock: 18,
      deliveryDays: 3,
      returnPolicy: '30-day return',
      attributes: { brand: 'CamVision', resolution: '4K', framerate: '30fps', mic: 'Dual' },
    },
    // gift_cards
    {
      merchantId: techMart.id,
      sku: 'TM-GC-500',
      title: '₹500 Gift Card',
      description: 'TechMart digital gift card valued at ₹500. A perfect small gift for buying cables, cases, or accessories. Sent directly to email.',
      category: 'gift_cards',
      price: 50000,
      stock: 999,
      deliveryDays: 1,
      returnPolicy: 'No returns',
      attributes: { type: 'Digital', value: '500 INR' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-GC-1000',
      title: '₹1,000 Gift Card',
      description: 'TechMart digital gift card valued at ₹1,000. Give the gift of technology and gadgets. Redeemable online immediately after purchase.',
      category: 'gift_cards',
      price: 100000,
      stock: 999,
      deliveryDays: 1,
      returnPolicy: 'No returns',
      attributes: { type: 'Digital', value: '1000 INR' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-GC-2500',
      title: '₹2,500 Gift Card',
      description: 'TechMart digital gift card valued at ₹2,500. Ideal for someone looking to upgrade their audio gear or peripheral devices.',
      category: 'gift_cards',
      price: 250000,
      stock: 999,
      deliveryDays: 1,
      returnPolicy: 'No returns',
      attributes: { type: 'Digital', value: '2500 INR' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-GC-5000',
      title: '₹5,000 Gift Card',
      description: 'TechMart digital gift card valued at ₹5,000. A substantial gift helping towards the purchase of a new smartphone or high-end electronics.',
      category: 'gift_cards',
      price: 500000,
      stock: 999,
      deliveryDays: 1,
      returnPolicy: 'No returns',
      attributes: { type: 'Digital', value: '5000 INR' },
    },
    {
      merchantId: techMart.id,
      sku: 'TM-GC-10000',
      title: '₹10,000 Gift Card',
      description: 'TechMart digital gift card valued at ₹10,000. The ultimate gift for a tech enthusiast. Can be applied to laptops, monitors, or any premium device.',
      category: 'gift_cards',
      price: 1000000,
      stock: 999,
      deliveryDays: 1,
      returnPolicy: 'No returns',
      attributes: { type: 'Digital', value: '10000 INR' },
    },
  ];

  for (const product of techMartProducts) {
    await prisma.product.create({ data: product });
  }

  console.log('Created Products');
  console.log('Seeded successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
